"""
schemas.py — Pydantic models for all LangGraph agent interactions in Project Chimera.

Every LLM node returns a structured JSON object validated against one of these models.
The GraphState TypedDict is the shared state object threaded through the entire graph.
"""
from __future__ import annotations

from enum import Enum
from typing import Any, Dict, Optional
from typing_extensions import TypedDict
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# LLM Output Schemas (force strict JSON from each agent node)
# ---------------------------------------------------------------------------

class ScoutOutput(BaseModel):
    """Output from the Scout node."""
    vulnerability_type: str = Field(
        default="unknown",
        description="Type of vulnerability detected"
    )
    affected_endpoints: list[str] = Field(
        default_factory=list,
        description="List of affected API endpoints or routes"
    )
    topography_summary: str = Field(
        default="Target mapped.",
        description="Summary of the target's attack surface"
    )
    recommended_approach: str = Field(
        default="Investigate for injection.",
        description="Recommended strategy"
    )


class InvestigatorOutput(BaseModel):
    """Output from the Investigator node."""
    hypothesis: str = Field(
        default="Testing vulnerability.",
        description="The suspected vulnerability vector"
    )
    exploit_payload: str = Field(
        description="The exact bash/curl command to run"
    )
    reasoning_steps: list[str] = Field(
        default_factory=list,
        description="Steps leading to this exploit"
    )
    confidence_score: float = Field(
        default=0.5,
        ge=0.0, le=1.0,
        description="Confidence score"
    )


class ArchitectOutput(BaseModel):
    """Output from the Architect node (Gemini 1.5 Pro)."""
    patched_content: str = Field(
        description="Complete patched file content (full file, not a diff) to fix the vulnerability"
    )
    files_modified: list[str] = Field(
        description="List of file paths modified by the diff"
    )
    explanation: str = Field(
        description="Plain English explanation of what the patch does and why it fixes the issue"
    )
    safe_to_apply: bool = Field(
        description="Whether the patch is safe to apply without breaking existing functionality"
    )


# ---------------------------------------------------------------------------
# LangGraph Shared State
# ---------------------------------------------------------------------------

class _GraphStateRequired(TypedDict):
    """Required fields — always present on every state object."""
    trace_id: str
    alert_payload: dict
    messages: list[dict]
    status: str
    iteration_count: int


class GraphState(_GraphStateRequired, total=False):
    """
    The single shared state object threaded through every node of the Chimera graph.
    SQLite MemorySaver checkpoints this after every node transition.

    Required fields are in _GraphStateRequired; all fields below are optional
    (absent until the node that sets them has run).
    """
    target_topography: str          # Attack surface summary from Scout
    current_hypothesis: str         # Active exploit hypothesis from Investigator
    scout_findings: str             # Full JSON dump of Scout results
    exploit_proof: str              # The payload that successfully captured the flag
    captured_flag: str              # Content of secrets table once captured
    remediation_patch: str          # Full patched file content generated by Architect
    original_source: str            # Pre-patch file content for rollback
    human_approved: Optional[bool]  # Set by /approve endpoint; None = pending
    failure_reason: str             # Why last exploit attempt failed (fed back to Investigator)
    current_node: str               # Name of the currently executing node


# ---------------------------------------------------------------------------
# Status Enum
# ---------------------------------------------------------------------------

class StatusEnum(str, Enum):
    queued = "queued"
    starting = "starting"
    scouting = "scouting"
    summarizing = "summarizing"
    investigating = "investigating"
    sandbox_running = "sandbox_running"
    evaluating = "evaluating"
    patching = "patching"
    awaiting_approval = "awaiting_approval"
    rollback = "rollback"
    resolved = "resolved"
    failed = "failed"
    rejected = "rejected"
    not_found = "not_found"
    unknown = "unknown"


# ---------------------------------------------------------------------------
# API Response Models
# ---------------------------------------------------------------------------

class StatusResponse(BaseModel):
    """Response model for GET /status/{trace_id}."""
    trace_id: str
    status: str
    iteration_count: int = 0
    current_node: Optional[str] = None
    has_flag: bool = False
    human_approval_pending: bool = False


# ---------------------------------------------------------------------------
# Webhook Ingress Validation
# ---------------------------------------------------------------------------

class AlertPayload(BaseModel):
    """Validated shape of an inbound SIEM alert webhook."""
    alert_id: Optional[str] = None
    type: Optional[str] = None
    target: Optional[Any] = None
    timestamp: Optional[str] = None
    evidence: Optional[str] = None
    severity: Optional[str] = "MEDIUM"
    source: Optional[str] = None
    trigger: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
