"""
schemas.py — Pydantic models for all LangGraph agent interactions in Project Chimera.

Every LLM node returns a structured JSON object validated against one of these models.
The GraphState TypedDict is the shared state object threaded through the entire graph.
"""
from __future__ import annotations

from typing import Any, Optional
from typing_extensions import TypedDict
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# LLM Output Schemas (force strict JSON from each agent node)
# ---------------------------------------------------------------------------

class ScoutOutput(BaseModel):
    """Output from the Scout node (Gemini 1.5 Flash)."""
    vulnerability_type: str = Field(
        description="Type of vulnerability detected (e.g. 'SQL Injection', 'XSS')"
    )
    affected_endpoints: list[str] = Field(
        description="List of affected API endpoints or routes"
    )
    topography_summary: str = Field(
        description="5-line max summary of the target's attack surface"
    )
    recommended_approach: str = Field(
        description="Recommended exploitation strategy for the Investigator"
    )


class InvestigatorOutput(BaseModel):
    """Output from the Investigator node (Groq Llama 3 70B)."""
    hypothesis: str = Field(
        description="The suspected vulnerability vector and why it should work"
    )
    exploit_payload: str = Field(
        description="The exact bash/curl command to run in the sandbox to exploit the vulnerability"
    )
    reasoning_steps: list[str] = Field(
        description="Step-by-step chain of thought leading to this exploit"
    )
    confidence_score: float = Field(
        ge=0.0, le=1.0,
        description="Confidence that this exploit will succeed (0.0-1.0)"
    )


class ArchitectOutput(BaseModel):
    """Output from the Architect node (Gemini 1.5 Pro)."""
    patched_content: str = Field(
        description="Complete patched file content (full file, not a diff) to fix the vulnerability"
    )
    files_modified: list[str] = Field(
        description="List of file paths modified by the diff"
    )
    explanation: str = Field(
        description="Plain English explanation of what the patch does and why it fixes the issue"
    )
    safe_to_apply: bool = Field(
        description="Whether the patch is safe to apply without breaking existing functionality"
    )


class VerifierOutput(BaseModel):
    """Output from the Verifier node."""
    exploit_blocked: bool = Field(
        description="True if the patched application successfully blocked the original exploit"
    )
    evidence: str = Field(
        description="The sandbox output proving the exploit was blocked or succeeded"
    )
    recommendation: str = Field(
        description="Next action: 'resolved', 'rollback', or 'retry_patch'"
    )


# ---------------------------------------------------------------------------
# LangGraph Shared State
# ---------------------------------------------------------------------------

class GraphState(TypedDict):
    """
    The single shared state object threaded through every node of the Chimera graph.
    SQLite MemorySaver checkpoints this after every node transition.
    """
    trace_id: str                   # UUID4 unique run identifier
    alert_payload: dict             # Raw webhook payload from SIEM
    messages: list[dict]            # Rolling last-5 agent turns (role + content)
    target_topography: str          # Attack surface summary from Scout
    current_hypothesis: str         # Active exploit hypothesis from Investigator
    scout_findings: str             # Full JSON dump of Scout results
    exploit_proof: str              # The payload that successfully captured the flag
    captured_flag: str              # Content of /flag.txt once captured
    remediation_patch: str          # Full patched file content generated by Architect
    original_source: str            # Pre-patch file content for rollback
    status: str                     # scouting | investigating | patching | resolved | failed
    iteration_count: int            # Loop guard — Evaluator routes to HumanReview at >= 10
    retry_count: int                # Transient failure tracker for API/Docker errors
    human_approved: Optional[bool]  # Set by /approve endpoint; None = pending
    failure_reason: str             # Why last exploit attempt failed (fed back to Investigator)
